# Filename: docker-compose.yaml
# Purpose: Compose file to set up Node.js and MongoDB containers for the MovieHub project.
#
# Common Commands:
#   Build & start containers in background:  docker-compose up --build -d
#   Stop and remove containers:              docker-compose down
#   Open MongoDB shell:                      docker-compose exec docker_mongo mongosh
#   Open Node.js container terminal:         docker-compose exec docker_node bash
#   View Node.js logs:                       docker-compose logs docker_node
#
# Notes:
#   - MongoDB is accessible at: mongodb://mongo:27017/moviehub
#   - Node.js app will run at:  http://localhost:3000
#   - MongoDB data is persisted using named volume: mongo-data
#   - Access website @ http://localhost:3000/HomeTemplate/index_HomePage.html#

version: "3.8"

services:
  node_app:
    container_name: docker_node                # Name of the Node.js container
    build:
      context: .                               # Use current directory for Docker build
      dockerfile: Dockerfile.node                      # Specify Dockerfile (rename if needed)
    ports:
      - "3000:3000"                            # Expose app on localhost:3000
    environment:
      MONGO_URI: "mongodb://mongo:27017/moviehub"  # MongoDB connection string
    depends_on:
      - mongo                                  # Ensure MongoDB starts before Node app
    volumes:
      - .:/app                                 # Mount project directory into container
    restart: unless-stopped                    # Auto-restart unless manually stopped

  mongo:
    container_name: docker_mongo               # Name of the MongoDB container
    image: mongo                               # Use official MongoDB image
    ports:
      - "27017:27017"                          # Expose MongoDB on localhost:27017
    volumes:
      - mongo-data:/data/db                    # Persist MongoDB data
    restart: unless-stopped                    # Auto-restart unless manually stopped

volumes:
  mongo-data:                                   # Named volume for MongoDB persistence
